# Generated by Django 4.2.6 on 2023-11-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_drinks_aditional'),
    ]

    operations = [
        migrations.CreateModel(
            name='drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('img', models.ImageField(default=0, null=True, upload_to='static/')),
            ],
        ),
        migrations.DeleteModel(
            name='drinks',
        ),
    ]
