# Generated by Django 4.2.6 on 2023-11-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_drink_delete_drinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='img',
            field=models.ImageField(blank=True, default=0, upload_to='static/'),
        ),
    ]
