# Generated by Django 4.2.6 on 2023-11-29 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aditional',
            name='product',
        ),
        migrations.DeleteModel(
            name='table',
        ),
        migrations.DeleteModel(
            name='aditional',
        ),
    ]
