# Generated by Django 4.2.6 on 2023-11-29 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_remove_aditional_product_delete_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('ingredient', models.TextField()),
                ('image', models.ImageField(upload_to='static/')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.category')),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
