# Generated by Django 4.2.6 on 2023-11-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_alter_plate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
