# Generated by Django 4.2.7 on 2023-11-14 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_product_image_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
